### ISSUE TITLE
Crash App

### ISSUE THREAD

**Issue by AshishGarg1988** [giangiu25307/Connection#1]
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.bluetooth.le.BluetoothLeAdvertiser.startAdvertising(android.bluetooth.le.AdvertiseSettings, android.bluetooth.le.AdvertiseData, android.bluetooth.le.AdvertiseCallback)' on a null object reference
                                                                                                    	at com.ConnectionProject.connection.Bluetooth.BluetoothAdvertiser.startAdvertising(BluetoothAdvertiser.java:107)
                                                                                                    	at com.ConnectionProject.connection.Controller.ConnectionController.initProcess(ConnectionController.java:366)
                                                                                                    	at com.ConnectionProject.connection.View.MapFragment$4.onClick(MapFragment.java:176)
                                                                                                    	at android.view.View.performClick(View.java:7201)

**Comment by rikyfaso** [comment]
hello ashishgarg, have you already turn on ble wifi gps ?
if you want a call with us to resolve your problem write me

**Comment by rikyfaso** [comment]
sorry for my late answer
